"""add_intraday_fno_pnl_to_snapshots

Revision ID: 1fb7cbf34697
Revises: 6ae34cf92fec
Create Date: 2026-03-12 21:51:08.698414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1fb7cbf34697'
down_revision: Union[str, None] = '6ae34cf92fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('claude_settings_user_id_key', 'claude_settings', type_='unique')
    op.drop_index('ix_claude_settings_user_id', table_name='claude_settings')
    op.create_index(op.f('ix_claude_settings_user_id'), 'claude_settings', ['user_id'], unique=True)
    op.add_column('portfolio_snapshots', sa.Column('intraday_pnl', sa.Float(), nullable=False, server_default='0'))
    op.add_column('portfolio_snapshots', sa.Column('fno_pnl', sa.Float(), nullable=False, server_default='0'))
    op.add_column('portfolio_snapshots', sa.Column('positions_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_snapshots', 'positions_json')
    op.drop_column('portfolio_snapshots', 'fno_pnl')
    op.drop_column('portfolio_snapshots', 'intraday_pnl')
    op.drop_index(op.f('ix_claude_settings_user_id'), table_name='claude_settings')
    op.create_index('ix_claude_settings_user_id', 'claude_settings', ['user_id'], unique=False)
    op.create_unique_constraint('claude_settings_user_id_key', 'claude_settings', ['user_id'])
    # ### end Alembic commands ###
